//! Integration tests for graylist pixel masking using real filter rules from
//! resources/complete-recipe.txt.
//!
//! Each test runs the full DeidPipeline against a synthetic DICOM fixture that
//! matches a specific graylist label, then verifies that pixels inside the
//! expected mask regions are zeroed (black) and pixels outside remain 255 (white).
//!
//! Fixtures are generated by: cargo run --example gen_test_data --features jpeg2000
//!
//! Requirement r-4-9

use dicom_dictionary_std::tags;
use dicom_object::open_file;
use std::collections::HashMap;
use std::fs;
use tempfile::TempDir;

use dicom_deid_rs::pipeline::{DeidConfig, DeidPipeline};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Run the full de-identification pipeline on a single fixture file using the
/// complete recipe, returning the output DICOM file path.
fn run_pipeline_on_fixture(
    fixture_name: &str,
) -> (std::path::PathBuf, dicom_deid_rs::pipeline::DeidReport) {
    let fixture_path = format!("tests/fixtures/graylist/{}", fixture_name);
    assert!(
        std::path::Path::new(&fixture_path).exists(),
        "Fixture {} not found. Run: cargo run --example gen_test_data --features jpeg2000",
        fixture_path
    );

    let tmp = TempDir::new().expect("should create temp dir");
    let input_dir = tmp.path().join("input");
    let output_dir = tmp.path().join("output");
    fs::create_dir_all(&input_dir).expect("create input dir");

    // Copy fixture into the temp input directory
    fs::copy(&fixture_path, input_dir.join(fixture_name)).expect("copy fixture");

    let mut variables = HashMap::new();
    variables.insert("PATIENT_ID".into(), "ANON-GRAYLIST".into());
    variables.insert("PATIENT_NAME".into(), "ANONYMOUS".into());
    variables.insert("DATEINC".into(), "0".into());

    let config = DeidConfig {
        input_dir: input_dir.clone(),
        output_dir: output_dir.clone(),
        recipe_path: "resources/complete-recipe.txt".into(),
        variables,
        functions: HashMap::new(),
        remove_private_tags: true,
    };

    let pipeline = DeidPipeline::new(config).expect("should create pipeline");
    let report = pipeline.run().expect("should run pipeline");

    let output_path = output_dir.join(fixture_name);
    // Leak the TempDir so it's not cleaned up before the caller reads the output
    std::mem::forget(tmp);
    (output_path, report)
}

/// Verify pixel masking on a DICOM object.
///
/// `mask_regions` are (xmin, ymin, xmax, ymax) rectangles that should be zeroed.
/// Pixels outside all mask regions should remain 255.
fn verify_pixel_masking(
    output_path: &std::path::Path,
    rows: usize,
    cols: usize,
    mask_regions: &[(usize, usize, usize, usize)],
) {
    let obj = open_file(output_path)
        .unwrap_or_else(|e| panic!("should open output file {}: {}", output_path.display(), e));

    let pixel_elem = obj
        .element(tags::PIXEL_DATA)
        .expect("output should have PixelData");
    let pixel_bytes = pixel_elem
        .value()
        .to_bytes()
        .expect("should read pixel bytes");

    assert!(
        pixel_bytes.len() >= rows * cols,
        "pixel data should have at least {} bytes, got {}",
        rows * cols,
        pixel_bytes.len()
    );

    // Check a sample of pixels inside mask regions are 0
    for &(xmin, ymin, xmax, ymax) in mask_regions {
        // Check corners and center of each mask region
        let sample_points = [
            (xmin, ymin),
            (xmax.saturating_sub(1), ymin),
            (xmin, ymax.saturating_sub(1)),
            (xmax.saturating_sub(1), ymax.saturating_sub(1)),
            ((xmin + xmax) / 2, (ymin + ymax) / 2),
        ];
        for (x, y) in sample_points {
            if x < cols && y < rows {
                let idx = y * cols + x;
                assert_eq!(
                    pixel_bytes[idx], 0,
                    "masked pixel ({},{}) should be 0, got {} (region ({},{},{},{}))",
                    x, y, pixel_bytes[idx], xmin, ymin, xmax, ymax
                );
            }
        }
    }

    // Check a sample of pixels outside ALL mask regions are 255
    let outside_points = find_outside_points(rows, cols, mask_regions);
    for (x, y) in outside_points {
        let idx = y * cols + x;
        assert_eq!(
            pixel_bytes[idx], 255,
            "unmasked pixel ({},{}) should be 255, got {}",
            x, y, pixel_bytes[idx]
        );
    }
}

/// Find sample points that are outside all mask regions.
fn find_outside_points(
    rows: usize,
    cols: usize,
    mask_regions: &[(usize, usize, usize, usize)],
) -> Vec<(usize, usize)> {
    let mut points = Vec::new();
    // Try the bottom-right corner area
    let candidates = [
        (cols - 1, rows - 1), // bottom-right corner
        (cols / 2, rows - 1), // bottom center
        (cols - 1, rows / 2), // right center
    ];
    for (x, y) in candidates {
        let inside_any = mask_regions
            .iter()
            .any(|&(xmin, ymin, xmax, ymax)| x >= xmin && x < xmax && y >= ymin && y < ymax);
        if !inside_any {
            points.push((x, y));
        }
    }
    assert!(
        !points.is_empty(),
        "should find at least one point outside all mask regions"
    );
    points
}

// ===========================================================================
// Uncompressed fixtures
// ===========================================================================

/// Fixture A: CT Dose Series (PHILIPS)
/// Graylist label at line 145 of complete-recipe.txt:
///   contains Modality CT + contains Manufacturer PHILIPS + contains ImageType DOSE
///   ctpcoordinates 0,0,512,135 → mask (0,0)-(512,135)
#[test]
fn graylist_ct_philips_dose() {
    let (output_path, report) = run_pipeline_on_fixture("ct_philips_dose.dcm");

    assert_eq!(
        report.files_processed, 1,
        "file should be processed (not blacklisted)"
    );
    assert_eq!(report.files_blacklisted, 0);

    verify_pixel_masking(
        &output_path,
        200, // rows
        512, // cols
        &[(0, 0, 512, 135)],
    );
}

/// Fixture B: LightSpeed Localizers
/// Graylist label at line 37 of complete-recipe.txt:
///   contains ManufacturerModelName LightSpeed VCT + contains Modality CT
///   + contains ImageType LOCAL
///   coordinates 0,0,80,85 → mask (0,0)-(80,85)
#[test]
fn graylist_ct_lightspeed_localizer() {
    let (output_path, report) = run_pipeline_on_fixture("ct_lightspeed_localizer.dcm");

    assert_eq!(
        report.files_processed, 1,
        "file should be processed (not blacklisted)"
    );
    assert_eq!(report.files_blacklisted, 0);

    verify_pixel_masking(
        &output_path,
        128, // rows
        128, // cols
        // This fixture matches multiple graylist labels that share the same
        // coordinates or have no coordinates. The net mask region is (0,0)-(80,85).
        &[(0, 0, 80, 85)],
    );
}

/// Fixture C: ATL HDI 5000
/// Graylist label at line 312 of complete-recipe.txt:
///   contains Modality US + contains Manufacturer ATL + equals Rows 476
///   + equals Columns 640 + contains ManufacturerModelName HDI 5000
///   ctpcoordinates 40,0,200,40 → (40,0,240,40)
///   ctpcoordinates 240,0,190,16 → (240,0,430,16)
#[test]
fn graylist_us_atl_hdi5000() {
    let (output_path, report) = run_pipeline_on_fixture("us_atl_hdi5000.dcm");

    assert_eq!(
        report.files_processed, 1,
        "file should be processed (not blacklisted)"
    );
    assert_eq!(report.files_blacklisted, 0);

    verify_pixel_masking(
        &output_path,
        476, // rows
        640, // cols
        &[(40, 0, 240, 40), (240, 0, 430, 16)],
    );
}

// ===========================================================================
// JPEG 2000 compressed fixtures (require jpeg2000 feature)
// ===========================================================================

/// Fixture D: Toshiba Aplio 400/500
/// Graylist label at line 401 of complete-recipe.txt:
///   contains Modality US + contains Manufacturer TOSHIBA + equals Rows 720
///   + equals Columns 960 + contains ManufacturerModelName A400|A500
///   ctpcoordinates 0,0,960,60 → (0,0,960,60)
#[cfg(feature = "jpeg2000")]
#[test]
fn graylist_us_toshiba_aplio() {
    let (output_path, report) = run_pipeline_on_fixture("us_toshiba_aplio.dcm");

    assert_eq!(
        report.files_processed, 1,
        "file should be processed (not blacklisted)"
    );
    assert_eq!(report.files_blacklisted, 0);

    verify_pixel_masking(
        &output_path,
        720, // rows
        960, // cols
        &[(0, 0, 960, 60)],
    );
}

/// Fixture E: Siemens Antares
/// Graylist label at line 337 of complete-recipe.txt:
///   contains Modality US + contains Manufacturer Siemens + equals Rows 768
///   + equals Columns 1024 + contains ManufacturerModelName Antares
///   ctpcoordinates 0,0,1024,60 → (0,0,1024,60)
///   ctpcoordinates 200,60,20,20 → (200,60,220,80)
///   ctpcoordinates 800,65,104,14 → (800,65,904,79)
#[cfg(feature = "jpeg2000")]
#[test]
fn graylist_us_siemens_antares() {
    let (output_path, report) = run_pipeline_on_fixture("us_siemens_antares.dcm");

    assert_eq!(
        report.files_processed, 1,
        "file should be processed (not blacklisted)"
    );
    assert_eq!(report.files_blacklisted, 0);

    verify_pixel_masking(
        &output_path,
        768,  // rows
        1024, // cols
        &[(0, 0, 1024, 60), (200, 60, 220, 80), (800, 65, 904, 79)],
    );
}

/// Fixture F: Philips IU22
/// Graylist label at line 224 of complete-recipe.txt:
///   contains Modality US + contains Manufacturer Philips + equals Rows 480
///   + contains ManufacturerModelName iU22
///   ctpcoordinates 0,0,640,47 → (0,0,640,47)
#[cfg(feature = "jpeg2000")]
#[test]
fn graylist_us_philips_iu22() {
    let (output_path, report) = run_pipeline_on_fixture("us_philips_iu22.dcm");

    assert_eq!(
        report.files_processed, 1,
        "file should be processed (not blacklisted)"
    );
    assert_eq!(report.files_blacklisted, 0);

    verify_pixel_masking(
        &output_path,
        480, // rows
        640, // cols
        &[(0, 0, 640, 47)],
    );
}
