/// Helper binary to generate graylist test fixtures for pixel masking tests.
///
/// Run with: cargo run --example gen_test_data --features jpeg2000
///
/// Creates 6 DICOM fixtures in tests/fixtures/graylist/:
///   - ct_philips_dose.dcm         (uncompressed, CT Dose Series PHILIPS)
///   - ct_lightspeed_localizer.dcm (uncompressed, LightSpeed Localizers)
///   - us_atl_hdi5000.dcm          (uncompressed, ATL HDI 5000)
///   - us_toshiba_aplio.dcm        (J2K Lossless, Toshiba Aplio 400/500)
///   - us_siemens_antares.dcm      (J2K Lossless, Siemens Antares)
///   - us_philips_iu22.dcm         (J2K Lossless, Philips IU22)
use dicom_core::value::{PrimitiveValue, Value};
use dicom_core::{DataElement, VR};
use dicom_dictionary_std::tags;
use dicom_object::FileDicomObject;
use dicom_object::meta::FileMetaTableBuilder;
use std::fs;

// ---------------------------------------------------------------------------
// JPEG 2000 Lossless codestreams (all-white monochrome, generated by Pillow)
// ---------------------------------------------------------------------------

/// J2K Lossless codestream for 960×720 all-white monochrome image (150 bytes)
#[rustfmt::skip]
const J2K_960X720: [u8; 150] = [
    0xff, 0x4f, 0xff, 0x51, 0x00, 0x29, 0x00, 0x00, 0x00, 0x00, 0x03, 0xc0, 0x00, 0x00, 0x02, 0xd0,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xc0, 0x00, 0x00, 0x02, 0xd0,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x07, 0x01, 0x01, 0xff, 0x52, 0x00,
    0x0c, 0x00, 0x00, 0x00, 0x01, 0x00, 0x05, 0x04, 0x04, 0x00, 0x01, 0xff, 0x5c, 0x00, 0x13, 0x40,
    0x40, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50,
    0xff, 0x64, 0x00, 0x25, 0x00, 0x01, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x20, 0x62, 0x79,
    0x20, 0x4f, 0x70, 0x65, 0x6e, 0x4a, 0x50, 0x45, 0x47, 0x20, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
    0x6e, 0x20, 0x32, 0x2e, 0x35, 0x2e, 0x34, 0xff, 0x90, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x1d, 0x00, 0x01, 0xff, 0x93, 0xcf, 0xb4, 0x1c, 0x14, 0x00, 0x5c, 0xaf, 0xfe, 0xd6, 0xd3, 0x80,
    0x80, 0x80, 0x80, 0x80, 0xff, 0xd9,
];

/// J2K Lossless codestream for 1024×768 all-white monochrome image (151 bytes)
#[rustfmt::skip]
const J2K_1024X768: [u8; 151] = [
    0xff, 0x4f, 0xff, 0x51, 0x00, 0x29, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x03, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x03, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x07, 0x01, 0x01, 0xff, 0x52, 0x00,
    0x0c, 0x00, 0x00, 0x00, 0x01, 0x00, 0x05, 0x04, 0x04, 0x00, 0x01, 0xff, 0x5c, 0x00, 0x13, 0x40,
    0x40, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50,
    0xff, 0x64, 0x00, 0x25, 0x00, 0x01, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x20, 0x62, 0x79,
    0x20, 0x4f, 0x70, 0x65, 0x6e, 0x4a, 0x50, 0x45, 0x47, 0x20, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
    0x6e, 0x20, 0x32, 0x2e, 0x35, 0x2e, 0x34, 0xff, 0x90, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x1e, 0x00, 0x01, 0xff, 0x93, 0xcf, 0xb4, 0x20, 0x14, 0x00, 0x5c, 0xaf, 0xff, 0x7f, 0xff, 0x7f,
    0x80, 0x80, 0x80, 0x80, 0x80, 0xff, 0xd9,
];

/// J2K Lossless codestream for 640×480 all-white monochrome image (150 bytes)
#[rustfmt::skip]
const J2K_640X480: [u8; 150] = [
    0xff, 0x4f, 0xff, 0x51, 0x00, 0x29, 0x00, 0x00, 0x00, 0x00, 0x02, 0x80, 0x00, 0x00, 0x01, 0xe0,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x80, 0x00, 0x00, 0x01, 0xe0,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x07, 0x01, 0x01, 0xff, 0x52, 0x00,
    0x0c, 0x00, 0x00, 0x00, 0x01, 0x00, 0x05, 0x04, 0x04, 0x00, 0x01, 0xff, 0x5c, 0x00, 0x13, 0x40,
    0x40, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50, 0x48, 0x48, 0x50,
    0xff, 0x64, 0x00, 0x25, 0x00, 0x01, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x20, 0x62, 0x79,
    0x20, 0x4f, 0x70, 0x65, 0x6e, 0x4a, 0x50, 0x45, 0x47, 0x20, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
    0x6e, 0x20, 0x32, 0x2e, 0x35, 0x2e, 0x34, 0xff, 0x90, 0x00, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x1d, 0x00, 0x01, 0xff, 0x93, 0xcf, 0xb4, 0x1c, 0x14, 0x00, 0x5c, 0xaf, 0xf1, 0x2a, 0x3f, 0x80,
    0x80, 0x80, 0x80, 0x80, 0xff, 0xd9,
];

// ---------------------------------------------------------------------------
// Tag helpers
// ---------------------------------------------------------------------------

struct FixtureTags {
    modality: &'static str,
    manufacturer: &'static str,
    model_name: &'static str,
    image_type: &'static str,
    series_description: &'static str,
    rows: u16,
    cols: u16,
    sop_instance_uid: &'static str,
}

fn put_str(
    obj: &mut FileDicomObject<dicom_object::InMemDicomObject>,
    tag: dicom_core::Tag,
    vr: VR,
    value: &str,
) {
    obj.put(DataElement::new(
        tag,
        vr,
        Value::Primitive(PrimitiveValue::from(value)),
    ));
}

fn put_u16(
    obj: &mut FileDicomObject<dicom_object::InMemDicomObject>,
    tag: dicom_core::Tag,
    vr: VR,
    value: u16,
) {
    obj.put(DataElement::new(
        tag,
        vr,
        Value::Primitive(PrimitiveValue::from(value)),
    ));
}

fn set_common_tags(obj: &mut FileDicomObject<dicom_object::InMemDicomObject>, t: &FixtureTags) {
    put_str(obj, tags::MODALITY, VR::CS, t.modality);
    put_str(obj, tags::MANUFACTURER, VR::LO, t.manufacturer);
    put_str(obj, tags::MANUFACTURER_MODEL_NAME, VR::LO, t.model_name);
    put_str(obj, tags::IMAGE_TYPE, VR::CS, t.image_type);
    if !t.series_description.is_empty() {
        put_str(obj, tags::SERIES_DESCRIPTION, VR::LO, t.series_description);
    }

    // Pixel format: 8-bit monochrome
    put_u16(obj, tags::ROWS, VR::US, t.rows);
    put_u16(obj, tags::COLUMNS, VR::US, t.cols);
    put_u16(obj, tags::BITS_ALLOCATED, VR::US, 8);
    put_u16(obj, tags::BITS_STORED, VR::US, 8);
    put_u16(obj, tags::HIGH_BIT, VR::US, 7);
    put_u16(obj, tags::PIXEL_REPRESENTATION, VR::US, 0);
    put_u16(obj, tags::SAMPLES_PER_PIXEL, VR::US, 1);
    put_str(obj, tags::PHOTOMETRIC_INTERPRETATION, VR::CS, "MONOCHROME2");

    // Tags required by the recipe's %header section
    put_str(obj, tags::PATIENT_NAME, VR::PN, "TEST^PATIENT");
    put_str(obj, tags::PATIENT_ID, VR::LO, "TEST-ID-001");
    put_str(obj, tags::STUDY_DATE, VR::DA, "20240101");
    put_str(obj, tags::SOP_INSTANCE_UID, VR::UI, t.sop_instance_uid);
    put_str(obj, tags::STUDY_INSTANCE_UID, VR::UI, "1.2.3.4.5.6.7.100");
    put_str(obj, tags::SERIES_INSTANCE_UID, VR::UI, "1.2.3.4.5.6.7.200");
}

// ---------------------------------------------------------------------------
// Generator functions
// ---------------------------------------------------------------------------

fn gen_uncompressed(filename: &str, t: FixtureTags) {
    let meta = FileMetaTableBuilder::new()
        .transfer_syntax("1.2.840.10008.1.2.1") // Explicit VR Little Endian
        .media_storage_sop_class_uid("1.2.840.10008.5.1.4.1.1.2") // CT Image Storage
        .media_storage_sop_instance_uid(t.sop_instance_uid)
        .implementation_class_uid("1.2.3.4")
        .build()
        .expect("valid file meta");

    let mut obj = FileDicomObject::new_empty_with_meta(meta);
    set_common_tags(&mut obj, &t);

    // All-white pixel data
    let pixel_count = (t.rows as usize) * (t.cols as usize);
    let pixels = vec![0xFFu8; pixel_count];
    obj.put(DataElement::new(
        tags::PIXEL_DATA,
        VR::OW,
        Value::Primitive(PrimitiveValue::U8(pixels.into())),
    ));

    let path = format!("tests/fixtures/graylist/{}", filename);
    obj.write_to_file(&path).expect("should write DICOM file");
    println!("Created {path}");
}

fn gen_j2k_compressed(filename: &str, t: FixtureTags, j2k_data: &[u8]) {
    let ts = "1.2.840.10008.1.2.4.90"; // JPEG 2000 Lossless

    // Use US Multi-frame Image Storage for US, CT Image Storage for CT
    let sop_class = if t.modality == "US" {
        "1.2.840.10008.5.1.4.1.1.3.1" // US Multi-frame Image Storage
    } else {
        "1.2.840.10008.5.1.4.1.1.2" // CT Image Storage
    };

    let meta = FileMetaTableBuilder::new()
        .transfer_syntax(ts)
        .media_storage_sop_class_uid(sop_class)
        .media_storage_sop_instance_uid(t.sop_instance_uid)
        .implementation_class_uid("1.2.3.4")
        .build()
        .expect("valid file meta");

    let mut obj = FileDicomObject::new_empty_with_meta(meta);
    set_common_tags(&mut obj, &t);

    // Encapsulated pixel data (JPEG 2000 codestream as single fragment)
    let pixel_data = DataElement::new(
        tags::PIXEL_DATA,
        VR::OB,
        Value::PixelSequence(dicom_core::value::PixelFragmentSequence::new(
            vec![0u32],
            vec![j2k_data.to_vec()],
        )),
    );
    obj.put(pixel_data);

    let path = format!("tests/fixtures/graylist/{}", filename);
    obj.write_to_file(&path).expect("should write DICOM file");
    println!("Created {path}");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fn main() {
    fs::create_dir_all("tests/fixtures/graylist").expect("create output dir");

    // A — CT Dose Series (PHILIPS): ctpcoordinates 0,0,512,135 → (0,0,512,135)
    gen_uncompressed(
        "ct_philips_dose.dcm",
        FixtureTags {
            modality: "CT",
            manufacturer: "PHILIPS",
            model_name: "Ingenuity CT",
            image_type: "ORIGINAL\\PRIMARY\\AXIAL\\DOSE",
            series_description: "Axial Series",
            rows: 200,
            cols: 512,
            sop_instance_uid: "1.2.3.4.5.6.7.8.100",
        },
    );

    // B — LightSpeed Localizers: coordinates 0,0,80,85
    gen_uncompressed(
        "ct_lightspeed_localizer.dcm",
        FixtureTags {
            modality: "CT",
            manufacturer: "GE MEDICAL SYSTEMS",
            model_name: "LightSpeed VCT",
            image_type: "ORIGINAL\\PRIMARY\\LOCALIZER",
            series_description: "Topogram",
            rows: 128,
            cols: 128,
            sop_instance_uid: "1.2.3.4.5.6.7.8.101",
        },
    );

    // C — ATL HDI 5000: ctpcoordinates 40,0,200,40 and 240,0,190,16
    //   → (40,0,240,40) and (240,0,430,16)
    gen_uncompressed(
        "us_atl_hdi5000.dcm",
        FixtureTags {
            modality: "US",
            manufacturer: "ATL",
            model_name: "HDI 5000",
            image_type: "ORIGINAL\\PRIMARY",
            series_description: "",
            rows: 476,
            cols: 640,
            sop_instance_uid: "1.2.3.4.5.6.7.8.102",
        },
    );

    // D — Toshiba Aplio 400/500: ctpcoordinates 0,0,960,60 → (0,0,960,60)
    gen_j2k_compressed(
        "us_toshiba_aplio.dcm",
        FixtureTags {
            modality: "US",
            manufacturer: "TOSHIBA",
            model_name: "TUS-A400",
            image_type: "ORIGINAL\\PRIMARY",
            series_description: "",
            rows: 720,
            cols: 960,
            sop_instance_uid: "1.2.3.4.5.6.7.8.103",
        },
        &J2K_960X720,
    );

    // E — Siemens Antares: ctpcoordinates 0,0,1024,60 + 200,60,20,20 + 800,65,104,14
    //   → (0,0,1024,60), (200,60,220,80), (800,65,904,79)
    gen_j2k_compressed(
        "us_siemens_antares.dcm",
        FixtureTags {
            modality: "US",
            manufacturer: "Siemens",
            model_name: "Antares",
            image_type: "ORIGINAL\\PRIMARY",
            series_description: "",
            rows: 768,
            cols: 1024,
            sop_instance_uid: "1.2.3.4.5.6.7.8.104",
        },
        &J2K_1024X768,
    );

    // F — Philips IU22: ctpcoordinates 0,0,640,47 → (0,0,640,47)
    gen_j2k_compressed(
        "us_philips_iu22.dcm",
        FixtureTags {
            modality: "US",
            manufacturer: "Philips",
            model_name: "iU22",
            image_type: "ORIGINAL\\PRIMARY",
            series_description: "",
            rows: 480,
            cols: 640,
            sop_instance_uid: "1.2.3.4.5.6.7.8.105",
        },
        &J2K_640X480,
    );

    println!("\nAll graylist test fixtures generated successfully.");
}
